janitor:
  db:
    password: dbpwd
    recreate-db-on-start: false
    update-db-on-start: true
    uri: jdbc:postgresql://127.0.0.1:5432/${JANITOR_DATABASE_NAME:testdb}
    username: dbuser
  iam:
    # TODO(PF-81): Switch to use SAM instead of config file for user authZ.
    config-based-authz-enabled: true
    admin-user-list: '[]'
  primary:
    scheduler-enabled: true
  pubsub:
    track-resource:
      enabled: false
      project-id:
      subscription:
  server:
    port: 8080
  stackdriver:
    enabled: true
  stairway:
    db:
      password: dbpwd_stairway
      uri: jdbc:postgresql://127.0.0.1:5432/${STAIRWAY_DATABASE_NAME:testdb_stairway}
      username: dbuser_stairway
    force-clean-start: true
    max-parallel-flights: 40
    migrate-upgrade: true
    quiet-down-timeout: 20s
    terminate-timeout: 5s

spring:
  application:
    name: janitor
