openapi: 3.0.0
info:
  title: Cloud Resource Janitor
  description: |
    Janitor service to cleanup cloud resources created by Terra CRL.
  version: 0.0.1

servers:
- url: /

paths:
  '/status':
    get:
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
      - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

  '/api/janitor/v1/resource/{id}':
    parameters:
    - $ref: '#/components/parameters/Id'
    get:
      description: |
        Get the resource by id.
      operationId: getResource
      tags:
        - janitor
      responses:
        200:
          description: OK
          $ref: '#/components/responses/GetResponse'
        500:
          description: Get request error
          $ref: '#/components/responses/ErrorResponse'

components:
  parameters:
    Id:
      name: id
      in: path
      description: A UUID to used to identify an object in the janitor
      required: true
      schema:
        type: string
  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string
    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string
    ResourceDescription:
      type: object
      properties:
        id:
          description: The ID of the resource
          type: string

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'

    GetResponse:
      description: Response to Get calls
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceDescription'
